server:
  port: 9000
spring:
  application:
    name: "credit-score-service"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    shutdown:
      access: unrestricted

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10000ms
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
