spring:
  application:
    name: UserService
  security:
    user:
      name: raj
      password: 1234
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: chutiya22
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true